name: Hello world Workflow
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world action step
        run: echo "Hello world!"

      - name: Run some linux commands
        run: |
          echo "Running some linux commands..." 
          ls -la
          pw
          uname -a
          echo "Done running linux commands!" 