name: Hello world Workflow
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world action step
        run: echo "Hello world!"

      - name: Run some linux commands
        run: |
          echo "Running some linux commands..." 
          ls -la
          pwd
          uname -a
          echo "Done running linux commands!" 

      - name: check which tools installed in this runner
        run: |
          echo "Checking which tools are installed in this runner..." 
          which node
          node --version
          which npm
          npm --version
          which python
          python --version
          which java
          java -version
          aws --version
          echo "Done checking tools!"